#! /bin/bash

function attachOrKill() {
    local SESSION=${1}
    local KILL=${2}

    if (tmux has-session -t ${SESSION} > /dev/null 2>&1); then
        if [ "${KILL}" = "1" ]; then
            tmux kill-session -t ${SESSION}
        else
            tmux attach-session -t ${SESSION}
            exit 0
        fi
    fi
}

function newSession() {
    local SESSION=${1}
    local WORKINGDIR=${2}
    local AUXDIR=${3}
    local VIMRC=${4}
    local MYDISPLAY=${5}
    local NOATTACH=${6}
    local VIRTUAL_ENV=${7}
    local NVM_USE=${8}

    tmux new-session -d -c ${WORKINGDIR} -s ${SESSION} -n main -e VIMINIT="source ${VIMRC}" -e VIRTUAL_ENV=${VIRTUAL_ENV} -e NVM_USE=${NVM_USE}

    threeVerticalPaneWindow ${SESSION} ${WORKINGDIR} ${AUXDIR} ${MYDISPLAY} 0

    if [ "${NOATTACH}" = "0" ]; then
        tmux attach-session -t ${SESSION}
    fi
}

function threeVerticalPaneWindow() {
    local SESSION=${1}
    local WORKINGDIR=${2}
    local AUXDIR=${3}
    local MYDISPLAY=${4}
    local WINDOW=${5}

    tmux split-window -h -c ${WORKINGDIR} -t ${SESSION}:${WINDOW}
    tmux split-window -h -c ${WORKINGDIR} -t ${SESSION}:${WINDOW}

    tmux select-layout -t ${SESSION}:${WINDOW}.0 even-horizontal

    tmux split-window -v -c ${AUXDIR} -t ${SESSION}:${WINDOW}.2

    if [ "${MYDISPLAY}" = "laptop" ]; then
        tmux break-pane -s ${SESSION}:${WINDOW}.2
        tmux join-pane -s ${SESSION}:${WINDOW}.2 -t ${SESSION}:1 -h
    fi

    tmux select-window -t ${SESSION}:${WINDOW}
    tmux select-pane -t ${SESSION}:${WINDOW}.1

    if [ "${MYDISPLAY}" = "wide" ]; then
        # Widen the main/middle pane
        tmux select-pane -t ${SESSION}:${WINDOW}.0
        tmux resize-pane -L 10

        tmux select-pane -t ${SESSION}:${WINDOW}.1
        tmux resize-pane -R 10
    fi
}

APP=$1
KILL=0
NOATTACH=0
MYDISPLAY=wide

shift

while [[ $# -gt 0 ]]
do
    key="$1"

    case $key in
    --kill)
        KILL=1
        ;;
    --no-attach)
        NOATTACH=1
        ;;
    --display)
        DISPLAY=${2}
        shift
        ;;
    *)    # unknown option
        echo "Unknown argument ${key}"
        exit 1
        ;;
    esac

    shift
done

source $(dirname $(readlink -f $0))/.local/tmux-app-sessions

${APP} ${KILL} ${MYDISPLAY} ${NOATTACH}

